### ISSUE TITLE
Home: 2/3

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#109]
**Definição**

**Como** um usuário do site da SouJunior, 
**Gostaria** de ver depoimentos, mensagens sobre a organização
**Para** que eu possa ler e decidir se gostaria de me voluntariar.
__________________________________________________________________________________________________________

**Descrição** 

Para que o usuário se sinta motivado a fazer parte da SouJunior, alguns relatos deverão estar contidos na pagina inicial, na seção de "Depoimentos", para que tanto os mentores quanto os juniores sintam-se motivados a entrar no projeto.
___________________________________________________________________________________________________________

**Protótipos**

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?type=design&node-id=1703-9696&scaling=min-zoom&page-id=799%3A2970

![Image](https://user-images.githubusercontent.com/115566254/235677747-50c82b9a-0721-41ff-b1e9-14cfd2a5ac71.png)

___________________________________________________________________________________________________________

**Critérios de Aceite**

**1.** O Apoiador entrará no site da SouJunior;

**2.** A home deve ter uma **seção** dedicada a depoimentos de colaboradores.

**3.** O usuário poderá rolar a página do site e ir até a seção "Depoimentos" ou clicar em Depoimentos no menu para ser direcionado para seção "depoimentos"

![Image](https://user-images.githubusercontent.com/115566254/233364009-4fc6f4f6-5d0a-47db-930a-14a3cbebddba.png)

**4.** No canto esquerdo da Seção deverá constar fotos dos colaboradores perfiladas, abaixo das fotos terá o seguinte texto "**O que  dizem sobre nós"**

![Image](https://user-images.githubusercontent.com/115566254/235678283-4b5db983-d8ba-4837-9827-bfbeb65480ec.png)

**5.** No campo á direita uma foto do colaborador, na frente da foto seu nome e cargo.

**6.** Abaixo do nome e cargo do colaborador conterá o depoimento do mesmo. Os depoimentos seguem abaixo.

**7.** Caso o usuário queira passar para o próximo depoimento, uma seta tanto pra direita tanto pra esquerda será disponibilizada.

**_DEPOIMENTOS;_**

**Priscila Souza**
Função: UX/UI Designer

![Image](https://user-images.githubusercontent.com/115566254/230943344-4682fe2a-5f1b-4855-b0d8-637c1962b26f.jpg)

" Oi, sou a Priscila, UX/UI aqui na SouJunior e poder contribuir com a iniciativa é incrível!! Além de aprender muito com os desenvolvimentos de projetos, tenho a oportunidade de fazer networking e, com isso, trocar muitas experiências."

**Anderson Nunes** 
Função: Front-end

![Image](https://user-images.githubusercontent.com/115566254/230947656-61b1a0b2-d428-4609-92b4-53c80d17dc4b.jpeg)

"Fui voluntário na Sou Junior e pude aprender sobre diversos aspectos da área de desenvolvimento e empregabilidade, o que acabou me auxiliando em processos seletivos, construção do perfil profissional e como ser encontrado pelos tech recruiters, até que após 6 meses de participação meu 'sim' chegou."

**Ana Santos**
Front-end

![Image](https://user-images.githubusercontent.com/115566254/232350741-b6823b64-3553-4e1d-89a2-fb0e76a19b84.png)

"Atuar como Dev Front-end nesse projeto tem sido algo prazeroso em minha vida. Aqui tenho colocado em prática não só as minhas capacidades técnicas, estou fazendo amigos, estou tendo a oportunidade de criar laços, de crescer. Estamos sendo mentorados em diversas áreas, nós capacitando, não só nas hards skils, mas como também nas soft skils. Acredito que poucos projetos são tão imersivos como esse."

**Anna Claudia Andrade**
 UX/UI Designer

![Image](https://user-images.githubusercontent.com/115566254/232350976-7f22495d-a12e-4986-a884-c93041eeea20.jpeg)

"A SouJunior está me proporcionando ter uma vivência de trabalho como UX/UI Designer. Aplicar o conteúdo estudado em cursos, de forma prática, trabalhar em equipe com metodologias ágeis e me desenvolver profissionalmente, ao mesmo tempo que esse projeto está sendo construído."

**Caique Fonseca**
 Agilista

![Image](https://user-images.githubusercontent.com/115566254/233381054-5a9c1729-0e08-4cf0-b4ff-01dbd5301942.png)

"Ambientes controlados, como salas de aula de cursos, são distantes da realidade de trabalho, repletos de variáveis desconhecidas. Isso gera um vácuo para os aprendizes, dificultando o progresso, sem que os estágios possam preenchê-lo. A SouJunior resolve esse problema, sendo aberta para todos. É uma obra digital incrível, dinâmica e viva, construída pelos usuários. Como não se apaixonar por um propósito assim?"

**Priscyla Antônio de A. Ribeiro**
Mentora UX/UI Designer

![Image](https://user-images.githubusercontent.com/115566254/232487087-64f6a318-53d2-4e7f-8349-d0072f161c8e.jpg)

"A Sou Junior me desafia todos os dias com experiencias reais de trabalho: através da mentoria e do compromisso com o trabalho."

**Talita Bitencourt**
Associate Product Manager (APM)

![Image](https://user-images.githubusercontent.com/115566254/233381639-875761b6-56a5-4fa8-990d-b800c8f22cdf.jpeg)

"Para mim, a teoria só faz sentido quando consigo aplicá-la na prática. Na SouJunior, temos a oportunidade de fazer isso diariamente, o que torna nosso aprendizado muito mais efetivo."

**Eduardo Bezerra**
UX/UI Designer

![Image](https://user-images.githubusercontent.com/115566254/234005741-d85ad42d-3c97-44d6-ba3d-5987d8496535.jpg)

"É uma honra poder fazer parte da Sou Junior e colocar em prática o que venho estudando, tenho certeza que a cada dia ganho mais experiência e me torno um UX Designer melhor, e logo logo irei conquistar meu lugar no mercado de trabalho. Tudo isso graças a Sou Junior."

**Júlio Masson**
Business

![Image](https://user-images.githubusercontent.com/115566254/234007861-ffffb1ac-10c3-4a5e-ba72-0c86bac57180.jpeg)

"Na SouJunior colaboramos com outros participantes para construir ideias de forma única. Presenciar a excepcionalidade dos Juniores e estabelecer conexões é uma experiência enriquecedora. Na SouJunior não aprendemos apenas a trabalhar de forma inteligente e com as melhores práticas, mas também formamos parcerias e desfrutamos de um ambiente empolgante diariamente."

**Bianca Alessandra**
Tech Recruiter

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/598a43e2-85fa-4c2d-9891-a7d454d71027)

"Eu conheci o projeto da SouJunior quando estava estudando para ter mais segurança na área, e comecei assistindo as lives e as trocas eram incríveis pra mim, me ajudavam muito a me desenvolver e eu senti que precisava retribuir de alguma forma, então resolvi me inscrever como voluntária e fico muito feliz que posso participar de um projeto incrível assim. Hoje tenho com todas as áreas de Tecnologia que agrega muito para o meu conhecimento como Tech Recruiter."

**Thiago SIlva**
Associate Product Manager (APM)

![Image](https://user-images.githubusercontent.com/115566254/234291383-450d315d-5b4b-4504-9f9c-5636a7c8fb13.jpeg)

 

“Experiência real de trabalho em projetos construída por uma empresa de tecnologia!
A experiência SouJunior tem sido uma das melhores experiências desde que iniciei o meu processo de migração de carreira. A dinâmica e vivencia, com foco na entrega de valor e no aprendizado vai muito além dos cursos que fiz de Product Management."

Léa Cintra 
Associate Product Manager (APM)

![Image](https://user-images.githubusercontent.com/115566254/234976433-150a0d92-73df-4cc9-90a7-c8c8cd6557aa.jpeg)

Associate Product Manager (APM)

"Iniciei na SouJunior como APM, participando da primeira versão do site, onde a 'Experiência real de trabalho em projetos construída por uma empresa de tecnologia' foi a motivação para a minha transição de carreira. A partir do início dessa experiência, com a mentoria da Head de Produto Vanêssa Santana, os estudos em tecnologia ficaram mais fáceis e com clareza. Na SouJunior todos têm a possibilidade de aprender colocando a 'mão na massa', e isso faz a diferença." 

___________________________________________________________________________________________________________

**Informações Adicionais**

___________________________________________________________________________________________________________

**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.

- [ ] A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.

- [ ] O site está em conformidade com as especificações.

- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ] O site é acessível para usuários com deficiência.

- [ ] O tempo de carregamento da página é aceitável.

- [ ] O código foi testado por meio de testes automatizados.

- [ ] Os testes de aceitação do usuário foram realizados com sucesso.

- [ ] O design do site está de acordo com as diretrizes definidas.

- [ ] O site é esteticamente atraente e fácil de usar.

- [ ] A documentação do código é completa e atualizada.

- [ ] A documentação do usuário está disponível e é fácil de usar.

- [ ] O site foi implantado com sucesso no ambiente de produção.

- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by andyarauj0** [comment]
@RntSaturnino 

Acho que a **definição** pode ser na perspectiva do usuário e não do colaborador. A ideia é darmos tangibilidade à iniciativa, com as pessoas que fazem parte dela, para quem não conhece a SouJunior. Colocaria assim "Como um usuário do site da soujunior, eu gostaria de ver depoimentos, mensagens sobre a organização ..."

Na **descrição**, vale pensar que o usuário do site não é só o juninho. Temos outras pessoas que podem se interessar pela iniciativa. Eu deixaria “Para que o usuário se sinta motivado ...”

Critério 3, indicar que ao clicar em ‘depoimentos’, o usuário será direcionado para a parte respectiva do site;

Critério 4: “O que os colaboradores falam sobre nós”.. algumas pessoas não estão colaborando com a iniciativa, como o caso da Léa. Talvez usar “O que dizem sobre a SouJunior” harmonize melhor. O que acha?

Além disso, acho que ficaria legal recortar o protótipo e colocá-lo abaixo do critério de aceite. Ou, se não quiser recortar, sinalizar de alguma forma no protótipo sobre o que estamos querendo nesse critério de aceite.

Critério 5: A última observação do critério de aceite 4 cabe aqui também.

No mais, falta revisar os depoimentos kkkkry. Mas faço isso logo após :)

**Comment by RntSaturnino** [comment]
@andyarauj0 ajustes feitos

**Comment by RntSaturnino** [comment]
@edcabralc

**Comment by sabrinamir** [comment]
@limaricardo @wandersonDeve esta US está parada. Poderiam validar?

**Comment by sabrinamir** [comment]
@brcaua e @wandersonDeve  poderiam validar a parte de frontend e backend para finalizarmos esta US?

**Comment by brcaua** [comment]
Validado.
