### ISSUE TITLE
Ouvidoria

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#112]
________________________________________________________________________________________________

**Definição**

**Como** usuário, 
**Gostaria** de ter acesso a uma canal de forma eficiente e acessível 
**Para** que eu possa registrar minhas reclamações, sugestões ou elogios.

**Descrição**

Para que o usuário do site da SouJunior tenha espaço para contribuir para o crescimento da iniciativa uma pagina de ouvidoria será introduzido ao site.

_________________________________________________________________________________________________________

**Protótipos**

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=2056%3A10255&type=design&node-id=2133-12341&viewport=-7273%2C4558%2C0.26&scaling=scale-down-width

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/97e72ecc-4339-49a0-b6e9-5719eebf0021)

___________________________________________________________________________________________________________

**Critérios de Aceite**

**1.** O usuário entrará no site da SouJunior e poderá acessar a ouvidoria clicando em “ouvidoria” no menu  do rodapé;

**2.** O site deve ter uma pagina dedicada para a ouvidoria.

**3.** Ao clicar no Botão "ouvidoria" a pagina será atualizada para "ouvidoria"

**4.** Os dados do usuário deverão ser direcionados para o e-mail do "**Brandão**"; [wouerner@soujunior.tech].

**5.** No campo da pagina um texto explicativo deverá aparecer.

"Seja bem-vindo(a) à nossa Ouvidoria! Estamos sempre buscando maneiras de melhorar nossos produtos e serviços, e sua opinião é extremamente importante. Por isso, criamos um canal exclusivo para que você possa registrar suas reclamações e sugestões."

**6.** O usuário deverá informar seu nome completo obrigatoriamente.

- **O campo “Nome completo” deverá ter capacidade para 100 caracteres.**

**7.** O campo "e-mail" deve ser preenchido obrigatoriamente.

**8.** Para ser considerado um e-mail válido o mesmo dever conter o símbolo de @ + o domínio do e-mail + .com/.net/.br.

**- Caso o e-mail não siga os critérios de validação, então o sistema deverá apresentar uma mensagem abaixo do campo com a descrição: E-mail inválido.**

**9.** O usuário deverá ter acesso a um campo escrito **"selecione**" juntamente com uma seta no campo inferior a direita apontando para baixo.

![Image](https://user-images.githubusercontent.com/115566254/236218523-e8cfe8d7-001f-4523-93b7-792076400ce4.png)

**10.** Caso o usuário clique na seta uma lista em **dropdown** será apresentada contendo as seguintes opções "Sugestão" ,"Reclamação" e "elogio"

**11.** O Usuário deverá **obrigatoriamente** escolher uma das 3 opções, caso não faça, ao clicar em **enviar,** um aviso aparecerá ao lado do campo **"para seguir com o envio, escolha uma das opções"**

![Image](https://user-images.githubusercontent.com/115566254/236203696-dfc88902-c29b-4d18-8e24-397029643f5d.png)

**12.** Caso o usuário opte por "**Sugestão** quando a informação for enviada para o  **Brandão** no campo do e-mail assunto terá a informação "**sugestão**".

**13.** Caso o usuário opte por "**Reclamação** quando a informação for enviada para **Brandão** no campo do e-mail assunto terá a informação "**Reclamação**".

**14.** Caso o usuário opte por "**Elogio** quando a informação for enviada para **Brandão** no campo do e-mail assunto terá a informação "**Elogio**".

**15.** Um campo com caixa de texto de 3200 (Três mil e duzentos) caracteres será inserido para que o usuário possa descrever sua "**sugestão/reclamação/elogio**"

**16**. Um contador de caracteres será mostrado no campo superior a direita da caixa de texto para o usuário.

**17** Caso o Usuário ultrapasse o limite de caracteres o mesmo não conseguira digitar e o contador de caracteres ficará em vermelho. 

![Image](https://user-images.githubusercontent.com/115566254/236205934-a62b96c2-2093-4bba-8ec1-cf83e91db5b9.png)

**18.** O usuário deverá ter acesso ao botão "**Enviar**" para enviar os dados preenchidos.

**19.** Caso os campos obrigatórios não forem preenchidos, ao clicar em **"Enviar"** aparecerá uma mensagem em vermelho no campo não preenchido "o campo não foi preenchido";

**20.** Quando o usuário clicar em "**Enviar**", aparecerá uma pop-up com a mensagem "**Obrigado por ajudar a SouJunior a crescer**"  então o usuário será redirecionado para a "**home*

**22.** Após clicar em Voltar ou em qualquer parte que faça a pagina atualizar, aparecerá um pop-up com um botão escrito "**Você deseja mesmo cancelar?**" com a opção "sim" e "não";

**23.** Caso o usuário opte por "**sim**" ele será redirecionado para a "home";

**24.** Caso o usuário opte por "**não**" os dados continuarão preenchidos e ele deverá clicar em "**Enviar**" para enviar sua reclamação/sugestão.
___________________________________________________________________________________________________________

**Informações Adicionais**
Qualquer observação importante para melhorar o entendimento da User Story
___________________________________________________________________________________________________________

**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.

- [ ] A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.

- [ ] O site está em conformidade com as especificações.

- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ] O site é acessível para usuários com deficiência.

- [ ] O tempo de carregamento da página é aceitável.

- [ ] O código foi testado por meio de testes automatizados.

- [ ] Os testes de aceitação do usuário foram realizados com sucesso.

- [ ] O design do site está de acordo com as diretrizes definidas.

- [ ] O site é esteticamente atraente e fácil de usar.

- [ ] A documentação do código é completa e atualizada.

- [ ] A documentação do usuário está disponível e é fácil de usar.

- [ ] O site foi implantado com sucesso no ambiente de produção.

- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by RntSaturnino** [comment]
@andyarauj0 Bom dia Anderson segue a US pra validar 04/05/2023

**Comment by andyarauj0** [comment]
@RntSaturnino  segue as minhas observações:


Critério de aceite 1: Informar que o usuário pode acessar a ouvidoria clicando em “ouvidoria” no menu da home do site;

Vamos remover o critério de aceite 2.

No critério de aceite 3, explicar que a pagina será atualizada ao clicar no botão " ouvidoria";

Critério de aceite 10: Vamos mudar a frase  para algo como “para seguir com o envio, escolha uma das opções “

Colocar o critério de aceite 20 que fala sobre o e-mail do brandão após o critério 3;

Critério 14: inserir elogio entre as opções;

Depois do critério de aceite 14, vale inserir um critério de aceite explicando que o usuário terá visibilidade a um contador de caracteres;

Critério de aceite 22 : não entendi kk

**Comment by RntSaturnino** [comment]
@andyarauj0 correções feitas

**Comment by andyarauj0** [comment]
@RntSaturnino sobre o critério de aceite 21, qual mensagem aparece nesse pop-up?

Sobre o critério 22, acho que seria legal explicitar que essa mensagem aparece caso o usuário aperte em algum botão, seja de retroceder ou algum outro do menu, apenas caso tenha algum dado preenchido em algum campo da Ouvidoria. 

O que acha?

**Comment by EduBeserra** [comment]
Segue o link para o prototipo finalizado:

 https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=2056%3A10255&type=design&node-id=2133-12341&viewport=-7273%2C4558%2C0.26&scaling=scale-down-width

**Comment by EduBeserra** [comment]
![ss](https://github.com/SouJunior/site-soujunior/assets/124407716/98f241f9-a3d9-4279-b473-9d7e49814d60)

foto da ilustração usada na pagina

**Comment by anikape** [comment]
Boa noite,

em reunião com os mentores front-end, não será possível atender o ponto abaixo. 

22. Após clicar em Voltar ou em qualquer parte que faça a pagina atualizar, aparecerá um pop-up com um botão escrito "Você deseja mesmo cancelar?" com a opção "sim" e "não";


As próprias configurações do navegador abrem um alert o qual não possível estilizar. caso, vocês tenham visto em algum site, por favor, nos envia o link para pesquisarmos como foi feito.

![Image](https://github.com/SouJunior/site-soujunior/assets/104070821/eddb982a-5804-47db-9fee-b0c3e63e0c0d)

**Comment by sabrinamir** [comment]
@limaricardo @wandersonDeve esta US está parada. Poderiam validar?

**Comment by sabrinamir** [comment]
@brcaua e @wandersonDeve  poderiam validar a parte de frontend e backend para finalizarmos esta US?

**Comment by brcaua** [comment]
Revisado e aprovado.
