### ISSUE TITLE
Home 3/3

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#117]
___________________________________________________________________________________________________________

**Definição**

**Como** usuário, 
**Gostaria** de acessar uma área no site 
**Para** que eu possa me inscrever, fazer parte ou apoiar a inciativa e acessar as principais redes de contato.
___________________________________________________________________________________________________________

**Descrição**

Essa historia de usuário tem como objetivo apresentar na nossa home as formas de acesso a nossa iniciativa juntamente com as nossa redes sociais.
___________________________________________________________________________________________________________

**Protótipos**

![Image](https://user-images.githubusercontent.com/115566254/234582122-0fcd20c5-6702-4766-8953-0b550fc23c31.png)

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?type=design&node-id=1703-9696&scaling=min-zoom&page-id=799%3A2970
___________________________________________________________________________________________________________

**Critérios de Aceite**

**1**. Abaixo da secção **depoimentos** que está na seguinte User story (https://github.com/SouJunior/site-soujunior/issues/109) terá uma seção dedicada para convidar as pessoas para o projeto. 

**2**. Um texto no início da Seção com os seguintes dizeres “**Faça você também parte da nossa comunidade!**”

**3**. Abaixo do texto uma foto perfilada dos **Heads** será apresentada.

![Image](https://user-images.githubusercontent.com/115566254/233388146-ec67ea88-1ab3-4e9f-bd68-a5e95d48ba57.png)

**4**. O usuário verá abaixo da foto três opções para ele participar do projeto **SouJunior**. juntamente com texto de apresentação

_"Na SouJunior, há diversas maneiras de participar do projeto, tanto para juniores como para mentores ou apoiadores. Os interessados em colaborar podem ajudar na construção do projeto ou patrocinar a iniciativa como apoiadores ou parceiros. Há várias formas de participar e os interessados podem clicar em uma das categorias abaixo e preencher as informações solicitadas."_

No canto a direita do texto conterá as opções para fazer parte da SouJunior

**Sou Junior
Sou Mentor
Sou apoiador** 

**5**. Caso o usuário clique no sinal de mais (+)  ou no menu **Sou Junior** será apresentado um texto em **dropdown**, caso o usuário clique novamente no texto ele voltara ao estado anterior.

_"A SouJunior oferece uma oportunidade para pessoas interessadas em trabalhar na área de tecnologia, mas que ainda não têm experiência suficiente. Os candidatos podem se inscrever através de um formulário. As informações dos candidatos serão avaliadas quando houver vagas disponíveis para a área de interesse e o candidato será contatado para seguir o processo.."_

- O usuário se identificando com a forma de participar um botão com os dizeres “quero participar" será disponibilizado.
- Ao clicar no Botão quero participar esse forms será aberto: https://docs.google.com/forms/d/e/1FAIpQLScvTFXKZcesbcyy5obWKg5nzVv2-1vegkr6CswfNPLhPBBD-A/viewform

**6.** Caso o usuário clique no sinal de mais **(+)**  ou no menu **Sou mentor** será apresentado um texto em **dropdown**, caso o usuário clique novamente no texto ele voltara ao estado anterior.

_“A SouJunior busca profissionais atuantes no mercado de trabalho há pelo menos 6 meses para atuar como mentores. Os interessados devem preencher o formulário de inscrição e serão contatados quando houver demanda na área de atuação.”_

- O usuário se identificando com a forma de participar um botão com os dizeres “quero participar" será disponibilizado
- Ao clicar no Botão quero participar esse form será aberto: 
https://docs.google.com/forms/d/e/1FAIpQLScvTFXKZcesbcyy5obWKg5nzVv2-1vegkr6CswfNPLhPBBD-A/viewform

**7**. Caso o usuário clique no sinal de mais (+)  ou no menu **Sou apoiador** será apresentado um texto em dropdown, caso o usuário clique novamente no texto ele voltara ao estado anterior.

“_O projeto SouJunior busca pessoas interessadas em contribuir para o projeto de alguma forma, incluindo financiadores da iniciativa, divulgadores com canais no YouTube, podcast ou blog sobre tecnologia, especialistas dispostos a palestrar para profissionais Juniores de tecnologia, recrutadores e empresas que desejam contratar. Interessados devem se inscrever através do formulário e, posteriormente, contatados pela equipe responsável.”_

- O usuário se identificando com a forma de participar um botão com os dizeres “quero participar" será disponibilizado
- Ao clicar no Botão quero participar essa US será ativada https://github.com/SouJunior/products/issues/50

**8**. Abaixo da seção “Quero participar” indicaremos nossa redes sociais para os usuários

![Image](https://user-images.githubusercontent.com/115566254/233389810-83b28b77-6ff7-4037-8b51-018015b556d1.png)

 
Sendo elas;

**GitHUB** https://github.com/SouJunior
**Discord** https://discord.com/invite/soujunior-community-759176734460346423
**Linkedin** https://www.linkedin.com/company/soujunior/mycompany/
**Youtube** https://www.youtube.com/@soujuniortech
**Facebook** https://www.facebook.com/people/SouJunior/100086671131030
**Twitter** https://twitter.com/SouJunior_Tech
**Telegram** https://t.me/soujuniortech
**Twitch** https://www.twitch.tv/soujuniortech
**Instagram**https://www.instagram.com/soujunior.tech/
9. As redes sociais deverá conter foto com seus logos e caso o usuário clique em uma das redes ele será direcionado para rede em questão em um nova página.

___________________________________________________________________________________________________________

**[FOTOS DOS HEADS]**
![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/f3291ff7-7638-4c11-a2e2-f1ab681e7dad)
**Camila Barbosa - Head de Agilidade**
- LinkedIn: https://www.linkedin.com/in/camila-barbosa-s/
- Discord: Camila Barosa#2015

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/b812f55e-988c-4b98-b63b-43b423da490b)
**Davi Hora - Head de Dados**
- Linkedin : https://www.linkedin.com/in/davi-hora/ 
- Discord : Davi Hora#1651

![Image](https://user-images.githubusercontent.com/91374502/221202301-642172ba-fa2b-4667-bb5c-89fb012a6d0c.png)
**Júlio Massom - Head de Business**
- LinkedIn: https://www.linkedin.com/in/juliomasson/
- Discord: Júlio#6558

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/95022ffc-f347-4c7b-a148-eaa3588457af)
**Mateus Leonardo - Head de Mobile**
- LinkedIn: https://www.linkedin.com/in/mateusmatosleonardo/
- Discord: Mateus Leonardo#3609

![](https://user-images.githubusercontent.com/91637499/242334897-b0305b43-af08-494d-be70-02654dacde57.jpeg)
**Paulo Pinheiro - Head de Q&A**
- LinkedIn: https://www.linkedin.com/in/paru369/
- Discord: Paulo Pinheiro#5957

![Image](https://user-images.githubusercontent.com/91374502/221064893-94771aa2-5cd4-45dc-b728-a97e1855ce66.png)
**Rarielly Januário - Head de Tech Recruiting**
- LinkedIn: https://www.linkedin.com/in/rariellyjanuario/
- Discord: Rarielly Januário#0795

![Image](https://user-images.githubusercontent.com/91637499/236970198-8fb1234b-0541-4eb9-b83e-601fe5578c12.jpeg)
**Ricardo Lima - Head de Front End**
- LinkedIn: https://www.linkedin.com/in/ricardo-pereira-lima/
- Discord:  Ricardo Lima #4177

![](https://user-images.githubusercontent.com/91637499/242335202-404792a1-d89c-4ee5-87b1-12858e216228.png)
**Ronald Miranda - Head de DevOps**
- LinkedIn: https://www.linkedin.com/in/rmirandaa/
- Discord: RRonaldM#8474

![Image](https://user-images.githubusercontent.com/91374502/221064620-3243f095-9a74-4952-bfa1-dbd254f26201.png)
**Vanêssa Santana - Head de Produtos**
- LinkedIn: https://www.linkedin.com/in/vanessa-patricia/
- Discord: Vanêssa Santana#3595

![Image](https://user-images.githubusercontent.com/91637499/236969733-17daece8-6f02-476f-b3f7-9e23fb148721.jpeg)
**Vinícius Miguel - Head de UX**
- LinkedIn: https://www.linkedin.com/in/viniciuslmiguel/
- Discord:  Vinicius L Miguel #3045

![Image](https://user-images.githubusercontent.com/91374502/222701634-2c4376da-a8b9-4e5a-ba83-d33cf3bf7108.png)
**Wanderson Santos - Head de Back End**
- LinkedIn: https://www.linkedin.com/in/wandersongsantos/
- Discord: Wanderlavo#0827
________________________________________________________________________________________________

**Informações Adicionais**
Qualquer observação importante para melhorar o entendimento da User Story
___________________________________________________________________________________________________________

**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.

- [ ] A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.

- [ ] O site está em conformidade com as especificações.

- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ] O site é acessível para usuários com deficiência.

- [ ] O tempo de carregamento da página é aceitável.

- [ ] O código foi testado por meio de testes automatizados.

- [ ] Os testes de aceitação do usuário foram realizados com sucesso.

- [ ] O design do site está de acordo com as diretrizes definidas.

- [ ] O site é esteticamente atraente e fácil de usar.

- [ ] A documentação do código é completa e atualizada.

- [ ] A documentação do usuário está disponível e é fácil de usar.

- [ ] O site foi implantado com sucesso no ambiente de produção.

- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by andyarauj0** [comment]
@RntSaturnino 

**Definição:**
Acho que podemos simplificar. Segue uma sugestão : Como usuário, eu gostaria de acessar uma área no site para que eu possa me inscrever, fazer parte ou apoiar a inciativa e acessar as principais redes de contato. O que acha?

 Critério 1: “Abaixo dos depoimentos”... vamos reiterar que se trata de uma seção do site e que está descrita na US anterior (sinaliza o nome da US).
Para dar mais ênfase, pode mostrar o protótipo da home “cortada” entre a parte de ‘depoimentos’ e a parte do ‘Faça parte’.

Critério 4: segue uma sugestão de texto para essa seção:
Na SouJunior, há diversas maneiras de participar do projeto, tanto para juniores como para mentores ou apoiadores. Os interessados em colaborar podem ajudar na construção do projeto ou patrocinar a iniciativa como apoiadores ou parceiros. Há várias categorias de participação disponíveis e interessados podem preencher formulários para se candidatar.

Critério 5: segue uma sugestão de texto para essa seção:
A SouJunior oferece uma oportunidade para pessoas interessadas em trabalhar na área de tecnologia, mas que ainda não têm experiência suficiente. Os candidatos podem se inscrever através de um formulário. As informações dos candidatos serão avaliadas quando houver vagas disponíveis para sua área de interesse e o candidato será contatado para seguir o processo.

Critério 6: segue uma sugestão de texto para essa seção:
A SouJunior busca profissionais atuantes no mercado de trabalho há pelo menos 6 meses para atuar como mentores. Os interessados devem preencher o formulário de inscrição e serão contatados quando houver demanda na área de atuação.

Critério 7: 
O projeto SouJunior busca pessoas interessadas em contribuir para o projeto de alguma forma, incluindo financiadores da iniciativa, divulgadores com canais no YouTube, podcast ou blog sobre tecnologia, especialistas dispostos a palestrar para profissionais Juniores de tecnologia, recrutadores e empresas que desejam contratar. Interessados devem se inscrever através do formulário e, posteriormente,  contatados pela equipe responsável.

**Comment by RntSaturnino** [comment]
@andyarauj0 Ajustes feitos

**Comment by RntSaturnino** [comment]
@anikape @edcabralc atualizei as fotos dos Heads, são 10 no total (estão na própria US home 3/3). Pode desconsiderar as fotos do figma.

**Comment by sabrinamir** [comment]
@limaricardo @wandersonDeve esta US está parada. Poderiam validar?

**Comment by sabrinamir** [comment]
@brcaua e @wandersonDeve  poderiam validar a parte de frontend e backend para finalizarmos esta US?

**Comment by brcaua** [comment]
Validado.
