### ISSUE TITLE
Home 4/4 (Rodapé)

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#123]
**Definição**

**Como** Usuário
**Gostaria** de um rodapé informativo e funcional
**Para**  para encontrar rapidamente informações relevantes
___________________________________________________________________________________________________________

**Descrição**

Com o objetivo de aprimorar a experiência de navegação e oferecer uma jornada mais fluida, implementamos um rodapé com menu para facilitar a navegação do usuário:

___________________________________________________________________________________________________________

**Protótipos**

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=2211%3A10496&type=design&node-id=2459-13266&viewport=-685%2C4217%2C0.37&scaling=scale-down

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/45d0e879-3dd3-4e2f-8e2f-4875d8be9c38)

___________________________________________________________________________________________________________

**Critérios de Aceite**

**1.** O Apoiador entrará no site da SouJunior. Após acessar o site da SouJunior, o usuário deverá descer a barra de rolagem até o rodapé da pagina

**2.** A home deve ter um rodapé com os seguintes menus:

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/d37a9f3b-7e4e-4023-9153-8d7320349955)

**Conheça a SouJunior**

- Sobre nós
- Missão Visão e valores
- Nossas iniciativas

**Fale conosco**

- Faq
- Ouvidoria 
- faça parte

**3** No menu do rodapé caso o Usuário clique em **Sobre nós** ele será direcionando pra pagina correspondente 
https://github.com/SouJunior/site-soujunior/issues/93

**4** No menu do rodapé caso o Usuário clique em **Missão Visão e valores** ele será direcionando pra pagina correspondente 
https://github.com/SouJunior/site-soujunior/issues/124

**5** No menu do rodapé caso o Usuário clique em **Nossas inciativas** ele será direcionando pra seção da home "Nossas inciativas"

**6** No menu do rodapé caso o Usuário clique em **faq** ele será direcionando pra pagina correspondente 
https://github.com/SouJunior/site-soujunior/issues/87

**6** No menu do rodapé caso o Usuário clique em **ouvidoria** ele será direcionando pra pagina correspondente 
https://github.com/SouJunior/site-soujunior/issues/112

**7** No menu do rodapé caso o Usuário clique em **Faça parte** ele será direcionando pra seção da home "Faça parte"

**8**. As redes sociais deverá conter foto com seus logos e caso o usuário clique em uma das redes ele será direcionado para rede em questão em um nova página.

GitHUB https://github.com/SouJunior
Discord https://discord.com/invite/soujunior-community-759176734460346423
Linkedin https://www.linkedin.com/company/soujunior/mycompany/
Youtube https://www.youtube.com/@soujuniortech
Facebook https://www.facebook.com/people/SouJunior/100086671131030
Twitter https://twitter.com/SouJunior_Tech
Telegram https://t.me/soujuniortech
Twitch https://www.twitch.tv/soujuniortech
Instagram https://www.instagram.com/soujunior.tech/

  
**9** O rodapé será mostrando em todas as paginas do site SouJunior

___________________________________________________________________________________________________________

**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.

- [ ] A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.

- [ ] O site está em conformidade com as especificações.

- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ] O site é acessível para usuários com deficiência.

- [ ] O tempo de carregamento da página é aceitável.

- [ ] O código foi testado por meio de testes automatizados.

- [ ] Os testes de aceitação do usuário foram realizados com sucesso.

- [ ] O design do site está de acordo com as diretrizes definidas.

- [ ] O site é esteticamente atraente e fácil de usar.

- [ ] A documentação do código é completa e atualizada.

- [ ] A documentação do usuário está disponível e é fácil de usar.

- [ ] O site foi implantado com sucesso no ambiente de produção.

- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by RntSaturnino** [comment]
@EduBeserra

**Comment by RntSaturnino** [comment]
https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=799%3A2970&type=design&node-id=2573-11469&viewport=-3514%2C2276%2C0.11&scaling=scale-down-width

**Comment by sabrinamir** [comment]
@limaricardo @wandersonDeve esta US está parada. Poderiam validar?

**Comment by sabrinamir** [comment]
@brcaua e @wandersonDeve  poderiam validar a parte de frontend e backend para finalizarmos esta US?

**Comment by brcaua** [comment]
Validado.
