### ISSUE TITLE
Cabeçalho Home

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#125]
**Definição**

**Como** Usuário
**Gostaria** de um cabeçalho informativo e funcional
**Para**  para encontrar rapidamente informações relevantes
___________________________________________________________________________________________________________

**Descrição**

Com o objetivo de aprimorar a experiência de navegação e oferecer uma jornada mais fluida, implementamos um cabeçalho  para facilitar a navegação do usuário:
___________________________________________________________________________________________________________

**Protótipos**

![Image](https://user-images.githubusercontent.com/115566254/245810368-f56486e9-4dc8-4652-9224-3e95e839a6c3.png)

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=2%3A10&type=design&node-id=2462-15217&viewport=7425%2C-1753%2C0.33&scaling=contain&starting-point-node-id=218%3A1378&show-proto-sidebar=1
___________________________________________________________________________________________________________

**Critérios de Aceite**

**1.**  O usuário entrará no site da SouJunior. Após acessar o site,  visualizará nosso **cabeçalho**

**2.**  A home deve ter um cabeçalho com os seguintes menus:

Sobre nós
Nossa inciativas
Depoimentos 
Faça parte

**3.** No menu do cabeçalho caso o Usuário clique em **Sobre nós** ele será direcionando pra pagina correspondente 
https://github.com/SouJunior/site-soujunior/issues/93

**4.** No menu do cabeçalho caso o Usuário clique em **nossas iniciativas** ele será direcionando pra seção da home "nossas iniciativas"
 
**5.** No menu do cabeçalho caso o Usuário clique em **Depoimento** ele será direcionando pra seção da home " Depoimento"

**6.** No menu do cabeçalho caso o Usuário clique em **faça parte** ele será direcionando pra seção da home "faça parte"

**7.** O cabeçalho será mostrando em todas as paginas do site SouJunior
___________________________________________________________________________________________________________

**Informações Adicionais**
Qualquer observação importante para melhorar o entendimento da User Story
___________________________________________________________________________________________________________

**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.

- [x] A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [x] As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.

- [ ] O site está em conformidade com as especificações.

- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ] O site é acessível para usuários com deficiência.

- [ ] O tempo de carregamento da página é aceitável.

- [ ] O código foi testado por meio de testes automatizados.

- [ ] Os testes de aceitação do usuário foram realizados com sucesso.

- [ ] O design do site está de acordo com as diretrizes definidas.

- [ ] O site é esteticamente atraente e fácil de usar.

- [ ] A documentação do código é completa e atualizada.

- [ ] A documentação do usuário está disponível e é fácil de usar.

- [ ] O site foi implantado com sucesso no ambiente de produção.

- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by RntSaturnino** [comment]
@Vanessapcs 14/06

**Comment by RntSaturnino** [comment]
https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=799%3A2970&type=design&node-id=2573-11469&viewport=-3514%2C2276%2C0.11&scaling=scale-down-width

**Comment by sabrinamir** [comment]
@limaricardo @wandersonDeve esta US está parada. Poderiam validar?

**Comment by sabrinamir** [comment]
@brcaua e @wandersonDeve poderiam validar a parte de frontend e backend para finalizarmos esta US?

**Comment by brcaua** [comment]
Revisado e aprovado.
