### ISSUE TITLE
[Ouvidoria] Alterar para "Selecione o assunto"

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#126]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/112

- **DESCRIÇÃO DO BUG:** Na parte de seleção onde o usuário pode escolher entre sugestão, reclamação e elogio está escrito **'seleciona o assunto'**.

- **EVIDÊNCIA:**

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/76355269-b3a2-4ee2-9061-aff8d532d86b)

- **SOLUÇÃO:** Alterar a opção "Seleciona o assunto" para "**Selecione o assunto**".

**Comment by Vanessapcs** [comment]
@RntSaturnino pode seguir para Ready.

**Comment by edcabralc** [comment]
@RntSaturnino, @Vanessapcs corrigido: https://deploy-preview-148--soujunior.netlify.app/ouvidoria
