### ISSUE TITLE
[Ouvidoria] Todos os campos devem ter * de obrigatoriedade

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#127]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/112

- **DESCRIÇÃO DO BUG:** Os campos de obrigatoriedade não aparecem o * sinalizando a obrigação do preenchimento 

- **EVIDÊNCIA:**

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/76355269-b3a2-4ee2-9061-aff8d532d86b)

 - **SOLUÇÃO:** colocar * em todos os campos obrigatórios sendo eles 

**Nome completo
E-mail
Selecione assunto
Mensagem**

**Comment by Vanessapcs** [comment]
@RntSaturnino pode seguir com o card para Ready.

**Comment by anikape** [comment]
@RntSaturnino feito
