### ISSUE TITLE
[ouvidoria] Diminuir o botão de enviar

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#129]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/112

- **DESCRIÇÃO DO BUG:** Botão enviar está muito grande não seguindo o padrão das demais páginas. 

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/115566254/246532568-6660ba05-9d6a-470e-ba37-4d45a4210053.png)

- **SOLUÇÃO:** alterar o botão para ficar igual a Us (sou apoiador) https://github.com/SouJunior/products/issues/50

**Comment by Vanessapcs** [comment]
@RntSaturnino a @savannes já criou esse card. Pode excluir esse.
