### ISSUE TITLE
[ouvidoria*] Incluir botão limpar (para limpar todo o formulário)

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#130]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/112

- **DESCRIÇÃO DO Bug:** Incluir um botão para o usuário apagar todo o formulário

- **EVIDÊNCIA:**

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/b826b126-d19d-43f7-a6be-f94caba78769)

- **SOLUÇÃO:**  Incluir um botão para o usuário apagar todo o formulário, seguindo os seguintes critérios de aceite

**1**. Caso o usuário queira apagar aquilo que ele já escreveu nos campos da pagina "ouvidoria" então um botão "limpar" será disponibilizado

**2**. Após o usuário clicar em "limpar" os campos:

- Nome completo
- E-mail
- valide seu E-mail
- Selecione o assunto
- Mensagem  

Serão apagados.

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/e6fb3f87-a4ca-4921-bfa8-894303c237bd)

**Comment by Vanessapcs** [comment]
@RntSaturnino onde ficará esse botão? Qual a ação que deverá ser executada após sua seleção? Favor incluir o fluxo e comportamento deste botão no card.
