### ISSUE TITLE
[Ouvidoria] PopUP - Ajustar popUp

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#131]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/112

- **DESCRIÇÃO DO BUG:** PopUp acaba ficando sumido no meio do fundo preto e o texto faltou um sinal de "!"

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/115566254/246534666-92075486-bc01-4e25-8e99-e00f0706fbfa.png)

- **SOLUÇÃO:** Texto **"Obrigado por ajudar a SouJunior a crescer!** ajustar fundo do PopUp e colocar botão abaixo do texto 

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/46800ddf-be94-4628-8061-7e377b697937)

https://www.figma.com/file/vZW7WBF2WfTiiRjsSQRiFe/SouJunior---UI%2FUX?type=design&node-id=89-3&t=qOAQ4G91R2ZZR2Ak-0

**Comment by Vanessapcs** [comment]
@RntSaturnino o melhor é iniciar a frase com maíusculo e o botão ir para baixo.

**Comment by RntSaturnino** [comment]
imagens de apoio

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/3d4d3830-bd85-46ce-ac30-e07b9b52007c)
![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/a3c3ef35-198a-4ccd-ab35-1677735fa159)

**Comment by anikape** [comment]
Bom dia. Gostaria de ressaltar que no protótipo não havia modelo o popup. As únicas mudanças seriam a posição do botão e o ponto de exclamação? ou vão desenvolver algum modelo específico para ele?

**Comment by RntSaturnino** [comment]
@anikape Bom dia Ana. 

Na verdade vamos tentar alterar a cor também pois ficou sendo ofuscado com o fundo. Pedi a participação dos UX na planning justamente para eles nos ajuda nisso @EduBeserra Priscila (não consegui marcar)

**Comment by anikape** [comment]
@RntSaturnino feito
