### ISSUE TITLE
[Site] Padronização de Fontes

### ISSUE THREAD

**Issue by savannes** [SouJunior/site-soujunior#132]
*LINK DA US DE REFERÊNCIA:*
Ouvidoria: https://github.com/SouJunior/site-soujunior/issues/112
FAQ: https://github.com/SouJunior/site-soujunior/issues/87
Cadastro Sou Apoiador: https://github.com/SouJunior/products/issues/50
Sobre Nós: https://github.com/SouJunior/site-soujunior/issues/93
Home 1: https://github.com/SouJunior/products/issues/55
Home 2: https://github.com/SouJunior/site-soujunior/issues/109
Home 3: https://github.com/SouJunior/site-soujunior/issues/117

*DESCRIÇÃO DO BUG:* Padronizar tipo e tamanho de fonte para textos do mesmo tipo. 

*EVIDÊNCIA:*

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/78b4c667-ec9e-41ba-b1c9-a65690d2bdde)

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/8ccb2e33-85f8-4373-ab86-0003c7072ac2)

*SOLUÇÃO:* Usar a fonte Radio Canada sem serifa. Definir tamanhos para "Título", "Subtítulo", "Corpo do Texto" e "Label de Campos" e padronizar em todo o site.
Ex.: Todos os títulos devem estar com o mesmo tipo e tamanho de fonte.

**Comment by Vanessapcs** [comment]
@savannes sobre a "Solução", na parte "Todos os títulos devem estar com e tamanho de fonte." 

Devem estar com "o que?".

**Comment by edcabralc** [comment]
@savannes o time de UX, já definiu o padrão para as fontes? Tamanho e espessura.

**Comment by edcabralc** [comment]
Estamos com impedimento para seguir com essa demanda. As fontes precisam ser definidas pelo time de UI/UX

**Comment by RntSaturnino** [comment]
@EduBeserra consegue ajudar aqui?
