### ISSUE TITLE
[Site] Padronização de  Botões

### ISSUE THREAD

**Issue by savannes** [SouJunior/site-soujunior#133]
*LINK DA US DE REFERÊNCIA:* 
Fale Conosco: https://github.com/SouJunior/site-soujunior/issues/87
Ouvidoria: https://github.com/SouJunior/site-soujunior/issues/112
Sou Apoiador: https://github.com/SouJunior/products/issues/50

*DESCRIÇÃO DO BUG:* Os botões de envio de formulário não estão padronizados.

*EVIDÊNCIA:*

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/154be5c0-020c-4a36-a518-c93fa391f682)

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/df8d9ce6-3a3e-4413-8102-6ca7981853c6)

*SOLUÇÃO:*Todos os botões devem ser do mesmo tamanho, com mesmo tipo e tamanho de fonte e devem estar centralizados na página. Devem ter bordas arredondadas e seguir o tamanho do FAQ/ Faça Parte.
A primeira letra deve ser maiúscula e o resto minúscula sem negrito.

**Comment by Vanessapcs** [comment]
@savannes pode seguir com o card para Ready.

**Comment by anikape** [comment]
Wireframe FAQ

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?node-id=563-2741&scaling=min-zoom&page-id=133%3A305&starting-point-node-id=218%3A980


Por favor, confirmem se todos os botões devem ser como o modelo do protótipo acima e de fato centralizado em todas as paginas.

**Comment by savannes** [comment]
@anikape, os botões devem estar padronizados.
Pode utilizar como padrão o **tamanho** do wireframe (que é o mesmo que está na pagina FAQ) porém, gostaríamos que as bordas sejam arredondadas e eles estejam centralizados na página. Além disso, conforme pedido no card sobre padronização de fontes, os botões também precisam estar com o tipo e tamanho de fonte padronizado em todas as páginas.

**Comment by edcabralc** [comment]
@savannes sugiro alterar de bug para improvement, já que seguimos o que estava no wireframe. Entendemos que deve ser padronizado, mas o time vai focar em resolver os bugs e os implementos e mudanças seguem como próximas sprints.

**Comment by edcabralc** [comment]
@savannes o botão dentro do seção Nossas Iniciativas tem um visual diferente, vamos mudar ou manter?

**Comment by anikape** [comment]
Ed, eu havia mudado pra seguir o padrão, porém mantive o tamanho que ele já tinha  Seria bom verificar

**Comment by anikape** [comment]
@RntSaturnino feito
