### ISSUE TITLE
[Cabeçalho] Ajustar o link do "Faça Parte".

### ISSUE THREAD

**Issue by savannes** [SouJunior/site-soujunior#134]
*LINK DA US DE REFERÊNCIA:* https://github.com/SouJunior/site-soujunior/issues/125

*DESCRIÇÃO DO BUG:* No cabeçalho o link do "Faça Parte"está direcionando o usuário para a página de cadastro do Apoiador.

*EVIDÊNCIA:*

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/ee0362db-209d-46fb-a329-5f124dbcd623)

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/940b636f-17af-4032-91f2-3210996bd94d)

*SOLUÇÃO:* Ajustar o link para que o usuário seja direcionado a seção "Faça Parte"na Home.

**Comment by Vanessapcs** [comment]
@savannes incluir o print da área da Home que o Usuário deverá ser direcionado ao selecionar o item de menu "Faça Parte". Após isso, colocar a US em "Ready".

**Comment by edcabralc** [comment]
@savannes, corrigido! 

https://deploy-preview-103--soujunior.netlify.app/#participation
