### ISSUE TITLE
[Sou apoiador] Ajustar o erro de grafia no título

### ISSUE THREAD

**Issue by savannes** [SouJunior/site-soujunior#135]
*LINK DA US DE REFERÊNCIA:* https://github.com/SouJunior/products/issues/50

*DESCRIÇÃO DO BUG:* No título há um erro de grafia . Está escrito Sou Apoaidor.

*EVIDÊNCIA:*

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/b36d7e43-828f-439a-acd9-058227001753)

*SOLUÇÃO:* Ajustar o título para Sou Apoiador.

**Comment by Vanessapcs** [comment]
@savannes pode seguir com o card para Ready.

**Comment by edcabralc** [comment]
@Vanessapcs, @savannes corrigido: https://deploy-preview-148--soujunior.netlify.app/ouvidoria
