### ISSUE TITLE
[Sou apoiador] Retirar obrigatoriedade do campo "Como prefere ser chamado?"

### ISSUE THREAD

**Issue by savannes** [SouJunior/site-soujunior#136]
*LINK DA US DE REFERÊNCIA:*
Sou Apoiador: https://github.com/SouJunior/products/issues/50

*DESCRIÇÃO DO BUG:* O campo "Como prefere ser chamado?" está como obrigatório, diferente do solicitado na US referência.

*EVIDÊNCIA:*

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/b36d7e43-828f-439a-acd9-058227001753)

*SOLUÇÃO:* Retirar obrigatoriedade do campo "Como prefere ser chamado".

**Comment by Vanessapcs** [comment]
@savannes pode enviar o card para Ready.

**Comment by anikape** [comment]
@RntSaturnino feito
