### ISSUE TITLE
[Sou apoiador] Incluir mensagem informando sucesso ou não do envio do formulário

### ISSUE THREAD

**Issue by savannes** [SouJunior/site-soujunior#139]
*LINK DA US DE REFERÊNCIA:*
Sou Apoiador: https://github.com/SouJunior/products/issues/50

*DESCRIÇÃO DO BUG:* Quando o usuário aperta o botão de "Enviar" para enviar o formulário não aparece nenhuma mensagem informativa se foi enviado com sucesso ou se houve algum erro e qual erro aconteceu,  diferente do solicitado na US referência.

*EVIDÊNCIA:*

![Image](https://user-images.githubusercontent.com/91637499/246670053-0ac37a34-fa44-4801-bf8b-88355a2b6ec0.png)

*SOLUÇÃO:* Criar pop-up com status da operação:

- Se o formulário foi enviado com sucesso exibir mensagem: "Seu formulário foi enviado com sucesso!"
- Se houve erro no envio do formulário, exibir mensagem de acordo com o erro apresentado:

1. O usuário não preencher todos os campos obrigatórios. Mensagem: "Não foi possível enviar o formulário. Preencha os campos obrigatórios".
2. O usuário preencheu errado algum campo obrigatório. Mensagem: "Não foi possível enviar o formulário. Revise os campos obrigatórios".
3. Houve algum problema no Back End que impossibilitou o envio do formulário. Mensagem: "Não foi possível enviar o formulário. Tente novamente mais tarde ou  entre em contato conosco". (adicionar link para a página de FAQ nas palavras "entre em contato conosco")

**Comment by Vanessapcs** [comment]
@savannes pode enviar o card para Ready.

**Comment by anikape** [comment]
@RntSaturnino feito
