### ISSUE TITLE
[Sou apoiador] Ajustar validação do campo de telefone e confirmação de telefone

### ISSUE THREAD

**Issue by savannes** [SouJunior/site-soujunior#140]
*LINK DA US DE REFERÊNCIA:*
Sou Apoiador: https://github.com/SouJunior/products/issues/50

*DESCRIÇÃO DO BUG:* O usuário preenche o número do telefone no formato que está o place holder do campo mas aparece mensagem: "Telefone (com DDD) inválido".

*EVIDÊNCIA:*

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/6004f3e5-4241-413d-ac19-be1d08129bd0)

*SOLUÇÃO:* Ajustar o formato aceito pelo formulário para o formato que esta no place holder e ajustar a mensagem de erro para: "Telefone inválido. Preencher no seguinte formato: (DDD) xxxxxxxxx"

**Comment by Vanessapcs** [comment]
@savannes pode seguir com o card para Ready.

**Comment by anikape** [comment]
@RntSaturnino

**Comment by RntSaturnino** [comment]
@anikape oi Ana, continua dando erro quando tento validar o numero 

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/829d969f-2648-4e91-9043-efb47b85f55b)

**Comment by anikape** [comment]
![image](https://github.com/SouJunior/site-soujunior/assets/104070821/677e04d6-58bf-43cc-aaf4-7454e88d2364)

já identifiquei o problema: temos que por (xx)xxxx-xxxx ai o campo valida

Vou pedir ao Gabriel para ajustar
