### ISSUE TITLE
[Home/ Faça Parte] Ajustar texto na área de Sou Apoiador

### ISSUE THREAD

**Issue by savannes** [SouJunior/site-soujunior#141]
*LINK DA US DE REFERÊNCIA:*
Home 3: https://github.com/SouJunior/site-soujunior/issues/117

*DESCRIÇÃO DO BUG:* O texto da área de Sou Apoiador do Faça Parte da Home começa com "O projeto SouJunior".

*EVIDÊNCIA:*

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/38d818cc-9409-46e3-bf12-f28d958d0538)

*SOLUÇÃO:* O texto "O projeto SouJunior" deve ser alterado para "A SouJunior".

**Comment by Vanessapcs** [comment]
@savannes pode seguir com o card para "Ready".

**Comment by anikape** [comment]
@RntSaturnino feito
