### ISSUE TITLE
[Home/ Faça Parte] Atualizar Fotos Heads]

### ISSUE THREAD

**Issue by savannes** [SouJunior/site-soujunior#142]
*LINK DA US DE REFERÊNCIA:*
Home 3: https://github.com/SouJunior/site-soujunior/issues/117

*DESCRIÇÃO DO BUG:*  As Fotos dos Heads na área de Faça Parte da Home estão desatualizadas.

*EVIDÊNCIA:*

![Image](https://github.com/SouJunior/site-soujunior/assets/91637499/a082f3af-6c5e-4209-a082-bca6e993c8ad)

*SOLUÇÃO:* Atualizar as fotos da área de Faça Parte da Home conforme US Home 3/3 (https://github.com/SouJunior/site-soujunior/issues/117)

**Comment by Vanessapcs** [comment]
@savannes as fotos dos heads da US de referência estão desatualizadas. Precisa ser atualizado na US https://github.com/SouJunior/site-soujunior/issues/117 e, além disso, colocar os nomes, LinkedIn e Discord de cada um.

**Comment by edcabralc** [comment]
@Vanessapcs atualizado: https://deploy-preview-148--soujunior.netlify.app/
