### ISSUE TITLE
[Faq] Mensagem de pergunta enviada com sucesso

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#144]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/87

- **DESCRIÇÃO DO BUG:** Quando o usuário manda sua duvida não aparece uma mensagem de aviso que a mensagem foi enviada 

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/115566254/246823270-8fcdfaee-b227-4e87-bf00-f8aa6ddce203.png)

- **SOLUÇÃO:**  Inserir um PopUp com a seguinte mensagem após o usuário clicar em enviar sua pergunta  **"Pergunta enviada com sucesso!"**

![Image](https://user-images.githubusercontent.com/115566254/246824091-7a8fcd86-ceac-4a47-9b7a-8a8bbbbb5cb7.png)

**Comment by RntSaturnino** [comment]
@Vanessapcs

**Comment by Vanessapcs** [comment]
@RntSaturnino liberado para Ready.

**Comment by anikape** [comment]
@RntSaturnino recomendo que criem o modelo do popup (cores, tamanhos, etc). No wireframe não trás essa informação.

**Comment by anikape** [comment]
@RntSaturnino feito
