### ISSUE TITLE
[Faq] Mudar o texto "Olá! Como podemos de ajudar?"

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#145]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/87

- **DESCRIÇÃO DO BUG:** Texto "Olá! Como podemos de ajudar?" contem erro 

- **EVIDÊNCIA:**

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/1574977b-fe32-47dd-aeba-86b5de0aff67)

- **SOLUÇÃO:** Alterar texto para 

 "Olá! Como podemos te ajudar?"

**Comment by RntSaturnino** [comment]
@Vanessapcs

**Comment by edcabralc** [comment]
@RntSaturnino, corrigido!

https://deploy-preview-103--soujunior.netlify.app/faq
