### ISSUE TITLE
[Faq] Verificar o espaçamento entre os campos

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#146]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/87

- **DESCRIÇÃO DO BUG:**  existe uma diferença entre os espaçamentos 

- **EVIDÊNCIA:**

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/4161e314-65ca-45c9-bad0-3038da6a9b75)

- **SOLUÇÃO:**  Arrumar o espaçamento igual do figma

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/f22e109d-c1c3-43fc-bf14-22c5f3f7bbba)

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?node-id=563-2741&scaling=scale-down-width&page-id=133%3A305&starting-point-node-id=218%3A980

**Comment by Vanessapcs** [comment]
@RntSaturnino ok para Ready.
