### ISSUE TITLE
[Faq] Centralizar as opções (voluntario, apoiador, etc)

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#147]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/87

- **DESCRIÇÃO DO BUG:** O texto não está centralizado  (voluntario, apoiador e outros)

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/115566254/246823270-8fcdfaee-b227-4e87-bf00-f8aa6ddce203.png)

- **SOLUÇÃO:**   Centralizar AS OPÇÕES  (voluntario, apoiador, etc)

**Comment by Vanessapcs** [comment]
@RntSaturnino liberado para ready.

**Comment by edcabralc** [comment]
@Vanessapcs alterado: https://deploy-preview-148--soujunior.netlify.app/faq
