### ISSUE TITLE
[Home depoimentos] Deixar o cartão de tamanho padrão

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#149]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/109

- **DESCRIÇÃO DO BUG:**  Ao transitar os cards de depoimentos eles estão em padrão totalmente diferentes 

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/115566254/246836103-129b3848-2262-4f47-b017-8a40bc6cc899.png)
![Image](https://user-images.githubusercontent.com/115566254/246836102-22d0bdbd-67d1-463a-b5a1-169d9eb6271c.png)

- **SOLUÇÃO:**  Deixar os cards de depoimentos padronizado conforme o Figma

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?type=design&node-id=1703-9696&scaling=min-zoom&page-id=799%3A2970

**Comment by RntSaturnino** [comment]
@Vanessapcs

**Comment by Vanessapcs** [comment]
@RntSaturnino adicionar o link do Figma abaixo da proposta de solução e levar o card para Ready.

**Comment by savannes** [comment]
@edcabralc, revisamos os depoimentos. Pode considerar os texto da US referência. Neste caso, o tamanho padrão dos cartões deve ser o do maior depoimento.

**Comment by edcabralc** [comment]
@RntSaturnino, corrigido!

https://deploy-preview-103--soujunior.netlify.app/#depoimentos
