### ISSUE TITLE
[Home/depoimentos] Ajustar a quantidade de fotos a quantidade do Figma

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#150]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/109

- **DESCRIÇÃO DO BUG:**  Ao lado dos cards de depoimentos existem muitas fotos dos colaboradores  

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/115566254/246837688-994af25e-b79e-4beb-9c2b-776354ac7b4f.png)

**SOLUÇÃO:** Colocar 8 fotos dos depoentes apenas 

![Image](https://user-images.githubusercontent.com/115566254/246838234-dd3d85b9-8409-4880-b70c-9ed8439bc4ce.png)

**Comment by RntSaturnino** [comment]
@Vanessapcs

**Comment by Vanessapcs** [comment]
@RntSaturnino liberado para Ready. Acho que poderia ser uma melhoria.

**Comment by edcabralc** [comment]
@RntSaturnino corrigido!

https://deploy-preview-103--soujunior.netlify.app/#depoimentos
