### ISSUE TITLE
[Home/ Nossas Iniciativas] Esmaecer as estrelas

### ISSUE THREAD

**Issue by lairareis** [SouJunior/site-soujunior#151]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/products/issues/55

- **DESCRIÇÃO DO BUG:** Na parte da "SouJunior Talk" as estrelas estão brigando com a legenda.

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/98753928/246842164-837b2545-0d2e-47e9-b3e5-9c996df711a2.png)

- **SOLUÇÃO:** Esmaecer estrelas

**Comment by Vanessapcs** [comment]
@lairareis pode mover para Ready.

**Comment by anikape** [comment]
@RntSaturnino feito

**Comment by igords-goncalves** [comment]
Realizando alteração @anikape @RntSaturnino @edcabralc

**Comment by igords-goncalves** [comment]
Em relação a essa issue a diferença está justamente na opacidade dos elementos, a imagens utilizada no layout com textos e outros elementos tem uma opacidade diferente da  imagem disponibilizada para uso.

Imagem com elementos opacidade das estrelas em 50%


![Image](https://github.com/SouJunior/site-soujunior/assets/79734585/420646d6-1dd9-4f4c-b4a6-f044fd285357)

Imagem disponibilizada para o front-end opacidade das estrelas em 100%

![Image](https://github.com/SouJunior/site-soujunior/assets/79734585/8b06b065-3b22-4baf-95cd-cc1a026e964a)

**Comment by igords-goncalves** [comment]
Alteração realizada.



![Image](https://github.com/SouJunior/site-soujunior/assets/79734585/7c1a772d-6f19-45c6-9980-1faf56431d65)
