### ISSUE TITLE
[Home/ Nossas Iniciativas] Retirar a transição automática

### ISSUE THREAD

**Issue by lairareis** [SouJunior/site-soujunior#152]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/products/issues/55

- **DESCRIÇÃO DO BUG:** Na parte de "Nossas iniciativas" a transição de "SouJunior Lab" para "SouJunior Talk" está muito rápida impossibilitando a leitura.

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/98753928/246846419-a6bf6f33-246e-4fa2-b00d-b3be6499a4fb.png)

- **SOLUÇÃO:** Retirar a transição automática.

**Comment by Vanessapcs** [comment]
@lairareis pode mover para Ready.

**Comment by RntSaturnino** [comment]
@anikape durante nossos testes percebemos que a transição é muito curta pra ler os textos e um tempo maior ficaria demais, então decidimos tirar a transição automática

**Comment by anikape** [comment]
@RntSaturnino feito
