### ISSUE TITLE
[Sobre Nós] Mudar foto do Brandão

### ISSUE THREAD

**Issue by lairareis** [SouJunior/site-soujunior#154]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/93

- **DESCRIÇÃO DO BUG:**  Na parte "Entrevista o CEO da Sou Junior - Wouerner Brandão" o fundo está muito escuro e a foto quase não se destaca.

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/98753928/246850838-a155cf83-69b4-46a5-8683-28124eda8300.png)

IMAGEM NOVA:

![Image](https://github.com/SouJunior/site-soujunior/assets/98753928/b35bb012-e6b4-481f-a317-07801c8aafe1)

- **SOLUÇÃO**: Trocar a foto do Brandão

**Comment by lairareis** [comment]
@Vanessapcs

**Comment by Vanessapcs** [comment]
@lairareis nesse caso precisa entrar em contato com o Brandão, pedir uma nova foto e incluir no card. Providenciar isso e quanto fizer a mudança, mover para Ready.

Pode acessá-lo diretamente no discord.

**Comment by anikape** [comment]
@RntSaturnino feito
