### ISSUE TITLE
[Sobre Nós] Ajustar o Hero com cores

### ISSUE THREAD

**Issue by lairareis** [SouJunior/site-soujunior#155]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/93

- **DESCRIÇÃO DO BUG:** O Hero está com cores de pele pálidas.

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/98753928/246861093-44e8cd0d-f3ce-47ba-a9ae-afcfc93a145e.png)

- **REFERÊNCIA:**

![Image](https://github.com/SouJunior/site-soujunior/assets/98753928/84f9b308-40ab-4f37-a159-42cdce7a1033)

- **SOLUÇÃO:** Alterar as cores dos bonecos para cores de pele variadas.

**Comment by lairareis** [comment]
@Vanessapcs

**Comment by Vanessapcs** [comment]
@lairareis incluir a imagem do Hero do "Sou apoiador" para servir de referência. Depois disso, mover para Ready.

**Comment by igords-goncalves** [comment]
@anikape @edcabralc  peguei essa task para ajuste.

**Comment by anikape** [comment]
@RntSaturnino feito

**Comment by RntSaturnino** [comment]
@anikape Bom dia 
Aqui segui o antigo
