### ISSUE TITLE
[Sobre Nós] Diminuir as linhas do título

### ISSUE THREAD

**Issue by lairareis** [SouJunior/site-soujunior#156]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/93

- **DESCRIÇÃO DO BUG:** O texto depois do Hero "Uma experiência real de trabalho em uma empresa de tecnologia." pode ser reduzido em espaço.

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/98753928/246863817-f4d5749a-4b81-4f74-9fed-bd5ccf149f5a.png)

- **SOLUÇÃO:** Reduzir de 3 linhas ocupadas para 2 linhas.

**Comment by lairareis** [comment]
@Vanessapcs

**Comment by Vanessapcs** [comment]
@lairareis pode seguir para Ready.

**Comment by anikape** [comment]
@Vanessapcs feito
