### ISSUE TITLE
[Sobre Nós] Escrever "Sobre Nós" em branco

### ISSUE THREAD

**Issue by lairareis** [SouJunior/site-soujunior#157]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/93

- **DESCRIÇÃO DO BUG:** o "Sobre Nós" está com uma cor muito próxima do fundo dificultando a leitura.

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/98753928/246865525-8c8f6e6b-9a6e-44e2-8e4e-154f87925e6b.png)

- **SOLUÇÃO:** Alterar a cor do "Sobre Nós" para branco.

**Comment by Vanessapcs** [comment]
@lairareis pode seguir para Ready.

**Comment by edcabralc** [comment]
@lairareis, corrigido!

https://deploy-preview-103--soujunior.netlify.app/sobre-nos
