### ISSUE TITLE
[Sobre Nós] Justificar o texto

### ISSUE THREAD

**Issue by lairareis** [SouJunior/site-soujunior#158]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/93

- **DESCRIÇÃO DO BUG:** O texto abaixo de "Sobre Nós" está centralizado ficando um pouco bagunçado.

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/98753928/246868336-4fdeca82-c4ee-471c-9c4a-9a00135286f7.png)

- **SOLUÇÃO:** Alterar o texto para justificado.

**Comment by lairareis** [comment]
@Vanessapcs

**Comment by edcabralc** [comment]
@Vanessapcs textos justificados para web não é uma boa para web, isso dificulta a leitura. Recomendo alinhado a esquerda.

Links para entender os motivos:
https://thiagonasc.com/desenvolvimento-web/justificar-texto-na-web-boa-ou-ma-pratica
https://rockcontent.com/br/talent-blog/alinhamento-justificado-versus-a-esquerda/

**Comment by Vanessapcs** [comment]
@edcabralc ótimo! Pode ser alinhado a esquerda.

**Comment by edcabralc** [comment]
@lairareis, @Vanessapcs.  Texto alinha a esquerda!
