### ISSUE TITLE
[Sobre Nós] Alterar data de criação

### ISSUE THREAD

**Issue by lairareis** [SouJunior/site-soujunior#159]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/93

- **DESCRIÇÃO DO BUG:** Data de criação da SouJunior errada

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/98753928/246956125-9de965f1-1bbe-452d-ad3d-2958637935ab.png)

- **SOLUÇÃO:** Alterar "2019" para "2022"

**Comment by lairareis** [comment]
@Vanessapcs

**Comment by anikape** [comment]
@Vanessapcs feito
