### ISSUE TITLE
[Sobre Nós] Ajustar no texto o tempo de carreira para 6 anos

### ISSUE THREAD

**Issue by lairareis** [SouJunior/site-soujunior#162]
- **LINK DA US DE REFERÊNCIA:** https://github.com/SouJunior/site-soujunior/issues/93

- **DESCRIÇÃO DO BUG:** Ajustar o tempo de carreira do Brandão.

- **EVIDÊNCIA:**

![Image](https://user-images.githubusercontent.com/98753928/246852357-4fa282e0-84d0-46d3-a70f-d3ac04d7d713.png)

- **SOLUÇÃO:** Alterar de "5 - 6 anos" para "6 anos"

**Comment by lairareis** [comment]
@Vanessapcs

**Comment by edcabralc** [comment]
Já atualizado e em produção
