### ISSUE TITLE
[Faq] Trocar mensagem de obrigatoriedade dos campos

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#164]
**LINK DA US DE REFERÊNCIA:

- **DESCRIÇÃO DO BUG:**  Alterar as descrições de obrigatoriedade

- **EVIDÊNCIA:** 

![Image](https://user-images.githubusercontent.com/115566254/250276131-fee93296-2e9c-40fd-b534-fcbb77040489.png)

 **SOLUÇÃO** seguir os seguintes critérios de aceite

“Nome” para "O campo nome é obrigatório."
“email” para "O campo E-mail é obrigatório."

**Comment by igords-goncalves** [comment]
Modificação realizada e também realizados ajustes quanto ao espaçamento da mensagem de erro, tentei padronizar o espaçamento seguindo o padrão do formulário da pagina de ouvidoria.

Antes:

![Image](https://github.com/SouJunior/site-soujunior/assets/79734585/aa8b9545-ba1c-4a22-bca7-d9f38271e9f7),

Depois:,


![Image](https://github.com/SouJunior/site-soujunior/assets/79734585/2659fd09-5ce2-4e0f-a5f2-2a6908050193)
