### ISSUE TITLE
[Sou apoiador] Apagar dados após clicar em "enviar"

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#165]
**LINK DA US DE REFERÊNCIA:

- **DESCRIÇÃO DO BUG:** Quando o usuário clica em enviar e recebe o PopUp os campos não são apagados (a página não atualiza)

- **EVIDÊNCIA:** 

![Image](https://user-images.githubusercontent.com/115566254/250171656-cadf9754-901c-4725-b76d-7a1bc575df1d.png)

![Image](https://user-images.githubusercontent.com/115566254/250171565-a8a08188-6714-4f36-b1fd-8aa1a7156016.png)

 **SOLUÇÃO** seguir os seguintes critérios de aceite

1- Após o último campo, existirá um botão: "Enviar"
3- Quando o usuário clicar em "Enviar", aparecerá uma pop-up com a mensagem "Dados enviados com sucesso, logo nossa equipe entrará em contato com você"
4- Após o usuário clicar no “fechar” do popUp a página atualizará limpando os dados

**Comment by anikape** [comment]
@igords-goncalves  @edcabralc  estou com essa task

**Comment by anikape** [comment]
@RntSaturnino feito
