### ISSUE TITLE
[Home/sobre nós] Trocar foto do Head

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/site-soujunior#166]
*LINK DA US DE REFERÊNCIA:*

Sobre Nós: https://github.com/SouJunior/site-soujunior/issues/93
Home 3: https://github.com/SouJunior/site-soujunior/issues/117

*DESCRIÇÃO DO BUG:* Trocar foto da Head Rarielly pela da Daniele Oliveira
*EVIDÊNCIA:*

![Image](https://user-images.githubusercontent.com/115566254/250675653-069320e7-a716-428d-b838-fe8c9f64ea89.png)

![Image](https://user-images.githubusercontent.com/115566254/250675970-e50ee737-cde4-4fe8-876f-7f86d6bd2d2f.png)

*SOLUÇÃO:*  Trocar por essa imagem

![Image](https://user-images.githubusercontent.com/115566254/250676056-f40db53f-bf9c-48d6-90bc-37125e2c29c5.jpg)

**Comment by anikape** [comment]
@RntSaturnino @Vanessapcs além da foto, precisamos tb dos links das redes sociais dela.

Vou alterar a foto, mas fica pendente a alteração das redes sociais

**Comment by RntSaturnino** [comment]
LinkedIn: https://www.linkedin.com/in/daniele-oliveirapsi/
Discord: danioliveira#7940

**Comment by anikape** [comment]
@RntSaturnino feito

**Comment by wandersonDeve** [comment]
Atualizar foto do Head de backend


![Image](https://github.com/SouJunior/site-soujunior/assets/81826043/b19e5349-9935-4b4e-a36a-712f50b343d9)

**Comment by anikape** [comment]
@RntSaturnino feito
