### ISSUE TITLE
Alterar símbolo do Twitter

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/site-soujunior#204]
LINK DA US DE REFERÊNCIA: https://github.com/SouJunior/site-soujunior/issues/117

DESCRIÇÃO DO BUG: No rodapé da página, o ícone ainda está do Twitter, porém a plataforma mudou o nome para X.

EVIDÊNCIA:

![Image](https://github.com/SouJunior/site-soujunior/assets/146049420/0fec0ff6-608d-43a6-9e68-77e58f86d43e)

SOLUÇÃO: Deverá ser alterado o ícone da rede social Twitter para a rede social X.

![Image](https://github.com/SouJunior/site-soujunior/assets/146049420/cb691c0e-af67-469d-8600-08150e77624d)

**Comment by sabrinamir** [comment]
@hygorvaz  pode validar?

**Comment by hygorvaz** [comment]
Aprovado, @sabrinamir

**Comment by edcabralc** [comment]
PR enviado e aprovado pelo @brcaua #209
