### ISSUE TITLE
[Rodapé] Ajustar o link do "Faça Parte"

### ISSUE THREAD

**Issue by TayTeixeira** [SouJunior/site-soujunior#205]
LINK DA US DE REFERÊNCIA: [Home 4/4 (Rodapé)#123](https://github.com/SouJunior/site-soujunior/issues/123)

DESCRIÇÃO DO BUG: Na opção "Faça Parte" do rodapé, quando clicada, ao invés de levar o usuário para a seção "Faça você também parte da nossa comunidade!" da Home, está direcionando o usuário para a página de cadastro do Apoiador.

EVIDÊNCIA:

![Image](https://github.com/SouJunior/site-soujunior/assets/31568030/d2c28740-7fde-49a0-ae60-6d03dfb04d30)

![Image](https://github.com/SouJunior/site-soujunior/assets/31568030/32182927-07e9-4e1a-93f3-b3bfe95ed5d1)

SOLUÇÃO:  Configurar o link de forma que, ao clicar em 'Faça Parte' no rodapé, o usuário seja redirecionado para a seção "Faça você também parte da nossa comunidade!" na Home.

**Comment by TayTeixeira** [comment]
@hygorvaz , você pode validar por favor?

**Comment by edcabralc** [comment]
PR aprovado por @brcaua #211
