### ISSUE TITLE
Sobre nós

### ISSUE THREAD

**Issue by Leacyntra10** [SouJunior/site-soujunior#93]
**História de usuário - Sobre Nós**

1. Inserir texto sobre a SouJunior
2. Entrevista com o CEO com foto
3. Foto da equipe de Heads

**Definição**
**Como** usuário eu **gostaria** de acessar o site, **para** conhecer mais sobre a SouJunior.

**Descrição:**
"A página "Sobre Nós" do Site da SouJunior tem tem como objetivo apresentar aos usuários a história da Open Source SouJunior, além de contar um pouco da história do CEO da organização Wouerner Brandão.

**Protótipo** 

![Image](https://user-images.githubusercontent.com/124841403/224021476-ffd96f69-7822-4aa6-9335-0823e26e4755.png)

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/FAQ-Sou-Junior?node-id=279%3A2109&scaling=min-zoom&page-id=245%3A1030

**Critérios de aceite**

1. Para acesso ao "Sobre Nós", **o Usuário deverá selecionar o item de Menu "Sobre Nós" na Home do site Sou Junior**;

![Image](https://user-images.githubusercontent.com/124841403/223901174-edce0dc8-d228-47d7-86cf-56d3e66a8549.png)

2. Após selecionar a opção **Sobre Nós**, o usuário acessará a página. Visualizará um breve contexto sobre a história SouJunior e logo em seguida a entrevista com o **CEO Wouerner Brandão**;
3. Antes da entrevista, **deverá constar a foto do CEO SouJunior - Wouerner Brandão e as suas Redes Sociais:**
- LinkedIn: https://www.linkedin.com/in/wouerner/
- Discord: wouerner#0001
5. No final da entrevista deverá constar a foto da equipe de Heads da SouJunior.
6. Para o usuário retornar a página inicial do site SouJunior, deverá selecionar o botão de retroceder da página.
7. Ao clicar no botão do Linkedin ou do Discord, o usuário deverá ser informado de que ele será direcionado para uma nova página em outra aba, para que o Usuário possa continuar navegando no Site caso desejado.
8. Abaixo da imagem do Brandão, deve vir as imagens dos Heads que apoiam no gerenciamento dos times, com seus respectivos nomes e cargos. A frase que antecederá as imagens deverá ser a seguinte:

- **Conheça a Equipe de Heads que apoia o Brandão no gerenciamento dos times.**

**Sobre a Sou Junior**

O projeto SouJunior surgiu em 01 de Julho de 2019, a partir da insatisfação do idealizador Wouerner Brandão com  o mercado tech, quando percebeu que poucas pessoas tinham conhecimento ou experiência na  área da tecnologia. Atualmente contamos com mais de 120 voluntários.

Com o intuito de fomentar a ideia de levar conhecimento e aprendizado numa área em ascensão, Wouerner reuniu algumas pessoas com o mesmo propósito de criar o projeto SouJunior. Preparando assim os profissionais juniores para o mercado por meio da construção de produtos e do conhecimento prático do dia a dia de uma empresa de tecnologia, desde o início, colocando a “mão na massa”.

Para que essa iniciativa se torne real, contamos com um time de voluntários, desde iniciantes no mercado de tecnologia até profissionais experientes, que atuam como mentores e lideram os times.

A SouJunior contará com um portfólio de produtos que proporcionará visibilidade aos juniores, os conectando tanto aos profissionais de recrutamento, para que a tão almejada primeira experiência seja alcançada, quanto aos mentores que irão orientá-los em sua jornada profissional que está apenas começando.

Portanto, participar da SouJunior é uma grande chance de adquirir experiência e de participar de um projeto de alta visibilidade, com o amparo de uma rede de apoio, além do networking e conexão com novas oportunidades.

**Entrevista o CEO da Sou Junior - Wouerner Brandão**

Wouerner Brandão é natural de Brasília, casado, pai do Erik, reside no Recanto das Emas e recentemente trabalhou em órgãos federais em Brasília.

**Como e quando foi iniciar na carreira de tecnologia?**
Iniciei a carreira na área de tecnologia no ano de 2010 como estagiário, permanecendo 1 ano e 2 meses. Após essa experiência, conquistei uma colocação de contrato CLT.
Estudei bacharelado na área de sistemas por 4 anos, e nos últimos 12 anos atuo profissionalmente em programação nas linguagens de PHP e JavaScript, no cargo de desenvolvedor Sênior na empresa eNe Soluções.

**O que te motivou a criar a Open Source SouJunior?**
Depois de 5 - 6 anos de carreira já com uma boa bagagem de conhecimentos, via que em alguns lugares que trabalhei tinham estagiários. Mas estas empresas, geralmente não contratavam juniores, e eu estava sempre envolvido com a complementação de estudos dos estagiários. Depois que fiz 8 anos de carreira fui para o trabalho remoto, onde trabalho há 4 anos, mas perdi o acesso aos juniores. A partir daí, comecei a fazer mentorias on-line, durante 3 meses. 
Quando as mentorias terminavam ou alguns encontravam colocação no mercado, pensei em reformular o processo para ajudar mais pessoas. Logo, priorizei o meu Linkedin para ver qual era a demanda das pessoas na plataforma e levar benefícios às suas carreiras. Notei que a queixa principal na plataforma era a falta de experiência e pelo conhecimento que adquiri, percebi que para os juniores conseguirem uma experiência válida seria trabalhar com  projetos Open Source, mesmo sem qualquer tipo de remuneração e serem reconhecidos pelo mercado. Com isso tive a ideia de criar a Open Source SouJunior, para que os juniores pudessem atuar e adquirir experiência.

**O que você considera um diferencial da SouJunior em relação às outras comunidades de trabalho voluntário?**
O diferencial é que as pessoas migram para a SouJunior para ganhar experiência, criando projetos reais em grupo, em equipe e as outras comunidades são voltadas para cursos ou para tirar dúvidas.
Na SouJunior, o júnior inicia  interagindo com outras pessoas, aprendendo a trabalhar de fato em um projeto real, e assim adquirir experiência na prática.
Temos tech recruiter e quando o júnior se inscrever para participar do projeto, passará por um onboarding. O júnior terá um mentor na área específica em que irá atuar, com estrutura de Scrum, Produto, Agilidade e Desenvolvimento. Tudo o que se assemelha e se aproxima de uma empresa de médio e grande porte".

**Qual o seu plano para estimular o interesse das pessoas em relação a SouJunior e impactar tanto os curiosos quanto os voluntários de forma que eles permaneçam continuamente engajados em relação a essa iniciativa?**
A SouJunior está presente nas maiores Redes Sociais, mas na maioria delas percebemos que o conteúdo se perde no meio da diversidade de informações, como postagens, imagens e vídeos. Porém o LinkedIn foi uma grande surpresa, pois visualizamos um fluxo crescente e contínuo de pessoas querendo conhecer mais sobre a iniciativa. Então, além de manter essa rede atualizada de informações, lançamos o nosso Site para que as pessoas possam conhecer tanto o projeto, quanto o produto construído pelos nossos juniores, e isso gerou um impacto muito positivo dentro e fora da comunidade. Portanto, entendemos o quanto "o site é necessário para nós, porque se tornou um agregador de informações e um local onde as pessoas poderão ter o primeiro contato com o produto, reconhecerão o valor do projeto e se alinharão ao nosso propósito".

**Você acredita que a SouJunior é o que você idealizou?**
Sim. Em relação a ideia do projeto eu sempre tive o propósito de entregar duas coisas: a primeira era promover a experiência prática para os juniores, que mesmo sendo difícil mensurar atualmente, sabemos que está acontecendo. A segunda era a ideia de estabelecer o trabalho em equipe, a colaboração e o esforço conjunto, gerando resultados impactantes para a jornada profissional dessas pessoas. Podemos ver isto acontecendo principalmente no desenvolvimento dos nossos produtos, o que foi comprovado após a primeira entrega do nosso Site.

**Você acredita que a SouJunior te ajudou a evoluir profissionalmente?**
Com certeza eu evolui profissionalmente após a SouJunior. Na verdade, eu não tinha liderado equipes tão grandes, como as que a SouJunior tem hoje. As equipes que eu liderava anteriormente eram de 5 a 10 pessoas no máximo e agora a SouJunior tem 10 vezes mais voluntários. Então, com toda a certeza tem agregado bastante na minha carreira e também na questão de marketing pessoal, que me dá a oportunidade de conhecer outras pessoas e também outros projetos.

**Qual o maior desafio para você em ser o CEO da SouJunior?**
O maior desafio foi o recrutamento em alguns aspectos, por ser voluntariado. Outra questão é o desafio financeiro em colocar os projetos on-line, já que tudo se baseia em dolar, como hospedagem do site, seguidores e outras ferramentas que tem um custo alto. Desta forma e considerando um número grande de pessoas que temos no projeto, esse processo se torna bem mais complexo.

**Você pretende futuramente transformar a SouJunior numa empresa jurídica?**
Provavelmente não. Acredito que a SouJunior terá pequenos negócios para se sustentar, mas não a transformarei em uma empresa no formato total, com profissionais remunerados ou algo do tipo. Porém, se houvesse uma doação que comportasse isso, poderíamos pensar no assunto.

**[FOTO DO CEO SOUJUNIOR - WOUERNER BRANDÃO]**

![Image](https://user-images.githubusercontent.com/91374502/221065192-c4305d09-e0bf-43a0-bb87-65f425f409f7.png)

**[FOTOS DOS HEADS]**

![Image](https://user-images.githubusercontent.com/91374502/221064620-3243f095-9a74-4952-bfa1-dbd254f26201.png)
**Vanêssa Santana - Head de Produtos**
- LinkedIn: https://www.linkedin.com/in/vanessa-patricia/
- Discord: Vanêssa Santana#3595

**- Vinicius L Miguel**

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/3d8d0e1e-6518-41cb-842b-a2d272e758cc)

- **LinkedIn:** https://www.linkedin.com/in/viniciuslmiguel/
- **Discord:**:  Vinicius L Miguel #3045

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/34a86f8b-e3a1-45e1-973c-05045f1d9847)

** Camila Barbosa - Head de Agilidade**
- LinkedIn: https://www.linkedin.com/in/camila-barbosa-s/
- Discord: Camila Barosa#2015

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/5d459a50-4620-4765-9a95-2341a7740cdf)

**Ricardo Lima - Head de Front End**
- LinkedIn: https://www.linkedin.com/in/ricardo-pereira-lima/
- Discord:  Ricardo Lima #4177

![Image](https://user-images.githubusercontent.com/91374502/222701634-2c4376da-a8b9-4e5a-ba83-d33cf3bf7108.png)
**Wanderson Santos - Head de Back End**
- LinkedIn: https://www.linkedin.com/in/wandersongsantos/
- Discord: Wanderlavo#0827

![](https://user-images.githubusercontent.com/91637499/242334897-b0305b43-af08-494d-be70-02654dacde57.jpeg)
**Paulo Pinheiro - Head de Quality Assurance**
- LinkedIn: https://www.linkedin.com/in/paru369/
- Discord: Paulo Pinheiro#5957

![](https://user-images.githubusercontent.com/91637499/242335202-404792a1-d89c-4ee5-87b1-12858e216228.png)
**Ronald Miranda - Head de DevOps**
- LinkedIn: https://www.linkedin.com/in/rmirandaa/
- Discord: RRonaldM#8474

![Image](https://user-images.githubusercontent.com/91374502/221202301-642172ba-fa2b-4667-bb5c-89fb012a6d0c.png)
![Image](https://user-images.githubusercontent.com/91374502/221202300-09567c5d-e4c9-4087-b095-41aba2559e27.png)
**Júlio Massom - Head de Business**
- LinkedIn: https://www.linkedin.com/in/juliomasson/
- Discord: Júlio#6558

![Image](https://user-images.githubusercontent.com/91374502/221064893-94771aa2-5cd4-45dc-b728-a97e1855ce66.png)
**Rarielly Januário - Head de Tech Recruiting**
- LinkedIn: https://www.linkedin.com/in/rariellyjanuario/
- Discord: Rarielly Januário#0795

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/95022ffc-f347-4c7b-a148-eaa3588457af)

**Mateus Leonardo**

- LinkedIn: https://www.linkedin.com/in/mateusmatosleonardo/
- Discord: Mateus Leonardo#3609

![Image](https://github.com/SouJunior/site-soujunior/assets/115566254/b812f55e-988c-4b98-b63b-43b423da490b)

**Davi Hora (Head de Dados)**

Discord : Davi Hora#1651
Linkedin : https://www.linkedin.com/in/davi-hora/ 

**[INSPIRAÇÃO PARA UX]**

![Image](https://user-images.githubusercontent.com/124841403/224025226-ed73e11f-68b4-4341-a358-6ffa62a646c8.png)

![Image](https://user-images.githubusercontent.com/124841403/224025265-864aca3c-0c2a-4995-b304-c6e5b754ccec.png)

**Comment by Vanessapcs** [comment]
**Descrição:** Ajustar a descrição conforme segue: 
"A página "Sobre Nós" do Site da Sou Junior tem tem como objetivo apresentar aos usuários a história da Open Source SouJunior, além de apresentar o CEO da organização Wouerner Brandão (só confirma se escrevi corretamente)."

**Critérios de Aceite:**

1 - Os critérios 1 e 2 podem ser apenas um, conforme descrito a seguir:
Para acessar o "Sobre Nós", o Usuário deverá selecionar o item de Menu "Sobre Nós" na página inicial do site Sou Junior.

3- Ajustar para: " Após selecionar o item de Menu "Sobre Nós" na página inicial do site Sou Junior, o Usuário visualizará a história da SouJunior e a entrevista com o CEO Wouerner Brandão."

4- Que botão é esse? Caso tenha um botão "voltar", precisa estar no protótipo". Caso seja apenas um ícone de voltar, dê um print no ícone e cole no critério para entendermos de que componente você está falando. Por exemplo: 

Para o usuário retornar a página inicial do site SouJunior, então deverá selecionar o botão de retroceder 

![Image](https://user-images.githubusercontent.com/91374502/216787186-911cbf40-b6a4-4834-9dd7-49111f90fc52.png)

da página.

**Comment by Vanessapcs** [comment]
@Leacyntra10 

**ENTREVISTA:**

4 - Preciso que você me explique melhor a pergunta e a resposta da questão 4. Pode mandar um audio se achar melhor.

5 - Seguem ajustes na resposta.
"Sim. Em relação a ideia do projeto eu sempre tive o propósito de entregar duas coisas: a primeira era promover a experiência prática para os juniores, que mesmo sendo difícil mensurar atualmente, sabemos que está acontecendo. A segunda era a ideia de estabelecer o trabalho em equipe, a colaboração e o esforço conjunto, gerando resultados impactantes para a jornada profissional dessas pessoas. Podemos ver isto acontecendo principalmente no desenvolvimento dos nossos produtos, o que foi comprovado após a primeira entrega do nosso Site".

6 - Apenas um pequeno ajuste na resposta 6:
"Com certeza eu evolui profissionalmente após a SouJunior. Na verdade, eu não tinha liderado equipes tão grandes, como as que a SouJunior tem hoje. As equipes que eu liderava anteriormente eram de 5 a 10 pessoas no máximo e agora a SouJunior tem 10 vezes mais voluntários. Então, com toda a certeza tem agregado bastante na minha carreira e também na questão de marketing pessoal, que me dá a oportunidade de conhecer outras pessoas e também outros projetos".

7 - Apenas um pequeno ajuste na resposta 7:
"O maior desafio foi o recrutamento em alguns aspectos, por ser voluntariado. Outra questão é o desafio financeiro em colocar os projetos on-line, já que tudo se baseia em dolar, como hospedagem do site, seguidores e outras ferramentas que tem um custo alto. Desta forma e considerando um número grande de pessoas que temos no projeto, esse processo se torna bem mais complexo".

8 - Apenas um pequeno ajuste na resposta 8:
"Provavelmente não. Acredito que a SouJunior terá pequenos negócios para se sustentar, mas não a transformarei em uma empresa no formato total, com profissionais remunerados ou algo do tipo. Porém, se houvesse uma doação que comportasse isso, poderíamos pensar no assunto".

**Comment by Vanessapcs** [comment]
@Leacyntra10 eu reordenei as falas, mantive uma parte na íntegra e substitui algumas palavras pelos seus sinônimos. Veja se focu bom.

4. Qual o seu plano para estimular o interesse das pessoas em relação a SouJunior e impactar tanto os curiosos quanto os voluntários de forma que eles permaneçam continuamente engajados em relação a essa iniciativa?

A SouJunior está presente nas maiores Redes Sociais, mas na maioria delas percebemos que o conteúdo se perde no meio da diversidade de informações, como postagens, imagens e vídeos. Porém o LinkedIn foi uma grande surpresa, pois visualizamos um fluxo crescente e contínuo de pessoas querendo conhecer mais sobre a iniciativa. Então, além de manter essa rede atualizada de informações, lançamos o nosso Site para que as pessoas possam conhecer tanto o projeto, quanto o produto construído pelos nossos juniores, e isso gerou um impacto muito positivo dentro e fora da comunidade. Portanto, entendemos o quanto "o site é necessário para nós, porque se tornou um agregador de informações e um local onde as pessoas poderão ter o primeiro contato com o produto, reconhecerão o valor do projeto e se alinharão ao nosso propósito".

**Comment by Vanessapcs** [comment]
@Leacyntra10 

fiz só uma ordenação dos critérios na própria US (veja o que acha) e se estiver tudo ok, pode colocar em "Ready".

**Comment by Vanessapcs** [comment]
@Leacyntra10 sei que já colocamos a US em ready, mas pensei em algumas coisas aqui (veja se concorda). @andyarauj0 veja o que acha também:

- Nessa parte do "Sobre nós": O projeto SouJunior surgiu a partir da insatisfação do idealizador Wouerner Brandão com o mercado tech, quando percebeu que poucas pessoas tinham conhecimento ou experiência na área da tecnologia.
> Não seria interessante depois da palavra "surgiu", colocarmos "em <data ou ano que começou o projeto>"? Acho que seria bom as pessoas saberem quando tudo começou. 

- Pensei que seria legal colocarmos a foto em preto e branco. Isso seria um padrão em todas as páginas.

- No final da entrevista colocar em negrito a informação "Conheça a equipe de heads que auxilia o nosso CEO na organização desse projeto tão importante:".
> Aí em seguida colocar uma foto (em tamanho menor) de todos os heads, com seu nome, área de atuação e dois ícones (um do LinkedIn e outro do discord) para que as pessoas possam entrar em contato com eles, caso desejado. É importante colocar essas informações das redes do Brandão também, só não sei muito bem onde.
> Ao clicar no link das redes das pessoas, entao o Usuário seria redirecionado para a página de referência. Porém, é importante deixar claro que será aberta "uma nova pagina" em outra aba, para que o Usuário possa continuar navegando no Site caso desejado.

- Essa estrutura poderia ser replicada em todas as demais páginas das áreas, onde assim, mostraríamos todos que estão presentes na SJ.

- Para a manutenção dessa página, é importante que os heads comuniquem vocês sobre a saída e entrada de qualquer pessoa do time para que seja feito um card de atualização (mas aí na hora da entrevista você os deixa informados) para o time do site incrementar o produto. Caso um head saia ou seja contratado, eu avisarei para que voces entrem em contato com ele.

Que acham? Faz sentido?
@Leacyntra10 e @andyarauj0 caso faça, podem seguir com as atualizações. 
Qualquer dúvida me avisem.
Outro ponto, colocaremos esse padrão em todas as páginas das "Áreas de Atuação".

**Comment by andyarauj0** [comment]
@Leacyntra10 e @Vanessapcs 
Sobre o primeiro ponto, eu gosto sempre de usar números para dar mais corpo a informação. Por exemplo, se as pessoas souberem que a SJ tem +100 voluntários, essa info gera maior significância à iniciativa, principalmente pensando nos apoiadores. 

Sobre o ponto de apresentar Heads eu acho que faz sentido dar "nome Às cabeças". Me colocando na posição do usuário, eu gostaria de saber em detalhes quem faz parte da organização. Sobre replicar isso para as páginas das demais áreas, precisamos pensar nesse bem bolado de atualização das infos, para não ficar obsoleto. Nesse caso, ficaríamos com a responsabilidade de pensar nesse card de atualização ou conversaríamos com o time de tech recrutier? Acho que faz mais sentido essa info sair de lá e consolidarmos os ajustes aqui. O que dizem?

**Comment by Vanessapcs** [comment]
@RntSaturnino @Samueldiasp @Leacyntra10 @midigalvao @andyarauj0 

Ainda estou atualizando a foto dos heads, conforme eles vão me mandando.

**Comment by Samueldiasp** [comment]
Olá, pessoal! Fiz alguns ajustes nos Critérios de Aceite e também inseri um "Protótipo" da página. Poderiam avaliar?

Logo em seguida, gostaria de enviar o protótipo para o time de UX/UI.

@Vanessapcs @andyarauj0

**Comment by Samueldiasp** [comment]
Bom dia! Atualizei a US com as os links do LinkedIn e Discord de cada Head, a foto do Head de Data, o Protótipo e as inspirações para UX.

@Vanessapcs @andyarauj0

**Comment by anikape** [comment]
Bom dia,

Não localizei o discord do Wanderlavo#0827. Poderiam verificar se está correto e se possível passar o id do perfil dele.

**Comment by Vanessapcs** [comment]
@anikape o discord do Wanderson é: WandersonSantos#0827

**Comment by edcabralc** [comment]
Bom dia, @RntSaturnino! Consegue atualizar a lista de cago e nome dos Heads? Assim conseguimos atualizar em ambas as páginas, com esse conteúdo > #117 .

**Comment by RntSaturnino** [comment]
@edcabralc boa tarde! Atualizamos as fotos, valeu!

**Comment by sabrinamir** [comment]
@limaricardo @wandersonDeve esta US está parada. Poderiam validar?

**Comment by brcaua** [comment]
Revisado e aprovado.
